apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-23T09:03:35Z"
  labels:
    run: bash-pod
    my-label: test
  name: bash-pod
  namespace: default
  resourceVersion: "21476"
  uid: 851c2421-d2be-4e43-9a5e-221806aa1432
spec:
  containers:
  - command:
    - sh
    - -c
    - hostname > /tmp/hostname && sleep 1d
    image: bash
    imagePullPolicy: Always
    name: bash-pod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2xcsv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-2xcsv
    secret:
      defaultMode: 420
      secretName: default-token-2xcsv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-23T09:03:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-23T09:13:31Z"
    message: 'containers with unready status: [bash-pod]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-23T09:13:31Z"
    message: 'containers with unready status: [bash-pod]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-23T09:03:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://9f0d14256799a39f38ea497287871c7f10e930c437fe0b7e4ad643ea41cf80e0
    image: bash:latest
    imageID: docker-pullable://bash@sha256:7345c7c8e632ed2ed6b81c6e33fb91b56e3985b95d9b94092a82c8220ee8d788
    lastState: {}
    name: bash-pod
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://9f0d14256799a39f38ea497287871c7f10e930c437fe0b7e4ad643ea41cf80e0
        exitCode: 137
        finishedAt: "2021-05-23T09:09:41Z"
        reason: Error
        startedAt: "2021-05-23T09:03:44Z"
  hostIP: 192.168.64.7
  phase: Failed
  qosClass: BestEffort
  startTime: "2021-05-23T09:03:35Z"
