apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronjob1
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronjob1
    spec:
      parallelism: 2
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: cron-vol
              persistentVolumeClaim:
                claimName: task-pv-claim
          containers:
          - command:
            - bash
            - -c
            - hostname >> /tmp/vol/storage
            image: bash
            name: cronjob1
            volumeMounts:
              - name: cron-vol
                mountPath: /tmp/vol
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 4
status: {}
