apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-13T11:07:18Z"
  labels:
    env: prod
    team: storage
  name: database
  namespace: default
  resourceVersion: "2578"
  uid: 7bc05489-cf28-4a59-b2b4-887c1282effb
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: database
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-2xcsv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-2xcsv
    secret:
      defaultMode: 420
      secretName: default-token-2xcsv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-13T11:07:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-13T11:07:23Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-13T11:07:23Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-13T11:07:18Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f80a58e5a350532923d906a3645a641c51cc9b30cbf87254d71cd2422f6b96c7
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:df13abe416e37eb3db4722840dd479b00ba193ac6606e7902331dcea50f4f1f2
    lastState: {}
    name: database
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-13T11:07:23Z"
  hostIP: 192.168.64.7
  phase: Running
  podIP: 172.17.0.9
  podIPs:
  - ip: 172.17.0.9
  qosClass: BestEffort
  startTime: "2021-05-13T11:07:18Z"
