apiVersion: v1
kind: Pod
metadata:
  name: limited-pod
spec:
  containers:
  - name: memory-demo-ctr
    image: busybox
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
