apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-busybox
  name: nginx-busybox
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5; done
    image: busybox
    name: busybox
    volumeMounts:
    - mountPath: /var/log 
      name: busybox-volume
  - name: sidecar
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: nginx-volume
  volumes:
  - name: busybox-volume
    emptyDir: {}
  - name: nginx-volume
    emptyDir: {}
