apiVersion: v1
kind: Pod
metadata:
  name: mydb
spec:
  containers:
    - name: mydb
      image: mysql:5.7
      envFrom:
      - configMapRef:
          name: db-config
      - secretRef:
          name: db-secret
  restartPolicy: Never
