---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grant
spec:
  podSelector:
    matchLabels:
      app: nginx298
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: granted
