apiVersion: v1
kind: Service
metadata:
  name: nginx34
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx34
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
