apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ngninx-resources
  name: ngninx-resources
  namespace: pod-resources
spec:
  containers:
  - image: nginx
    name: ngninx-resources
    resources:
      requests:
        memory: "1Gi"
        cpu: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
