apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxredis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxredis
  template:
    metadata:
      labels:
        app: nginxredis
    spec:
      containers:
      - name: nginx
        image: nginx
