apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  containers:
  - args:
    - sleep
    - "9999"
    image: bash
    name: pod1
    volumeMounts:
    - name: foo
      mountPath: "/tmp/secret1"
    resources: {}
    envFrom:
      - configMapRef:
          name: drink1
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: foo
    secret:
      secretName: secret1
status: {}
