apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-29T09:07:36Z"
  labels:
    run: podswith2con
  name: podswith2con
  namespace: ggckad-s2
  resourceVersion: "139666"
  uid: 3bbf0545-2968-42de-bbd6-cf7945ed2753
spec:
  containers:
  - image: kubegoldenguide/alpine-spin:1.0.0
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
    imagePullPolicy: IfNotPresent
    name: con1
  - image: kubegoldenguide/alpine-spin:1.0.0
    securityContext:
      runAsUser: 2000
      runAsGroup: 3000
    name: con2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-h548n
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-h548n
    secret:
      defaultMode: 420
      secretName: default-token-h548n
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:07:36Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:07:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:07:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:07:36Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6c2032b9d1ffbf3554a95b519e5bfb8405bb40edec633967cc2ae3d49d18088b
    image: kubegoldenguide/alpine-spin:1.0.0
    imageID: docker-pullable://kubegoldenguide/alpine-spin@sha256:e4856b0e84f9e43d010ff7dc124e4c22ed58737c4da176439efe4223c106da5d
    lastState: {}
    name: podswith2con
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-29T09:07:37Z"
  hostIP: 192.168.64.7
  phase: Running
  podIP: 172.17.0.16
  podIPs:
  - ip: 172.17.0.16
  qosClass: BestEffort
  startTime: "2021-05-29T09:07:36Z"
