apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: admin
  containers:
  - image: nginx
    name: nginx
    args:
    - /bin/sh
    - -c
    - sleep 3600
