apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-05-29T09:15:40Z"
  labels:
    run: question-13-pod
  name: question-13-pod
  namespace: ggckad-s4
  resourceVersion: "140323"
  uid: d2fb334a-40dd-4e85-9462-a4ecc1d10069
spec:
  containers:
  - image: kubegoldenguide/question-thirteen
    imagePullPolicy: Always
    name: question-13-pod
    ports:
    - containerPort: 8000
    livenessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
    readinessProbe:
      httpGet:
        path: /health
        port: 8000
      initialDelaySeconds: 60
      periodSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-xblbq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-xblbq
    secret:
      defaultMode: 420
      secretName: default-token-xblbq
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:15:40Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:15:53Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:15:53Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-05-29T09:15:40Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://70b64a0b889437c6187e86c646169a155a5a16e43b2b036c3e7bfd24b1a568e3
    image: kubegoldenguide/question-thirteen:latest
    imageID: docker-pullable://kubegoldenguide/question-thirteen@sha256:61bbe55e047d9a708770e171060a1fef8aaad6247a1ff495bc5ac0edb10ac8fc
    lastState: {}
    name: question-13-pod
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-05-29T09:15:53Z"
  hostIP: 192.168.64.7
  phase: Running
  podIP: 172.17.0.17
  podIPs:
  - ip: 172.17.0.17
  qosClass: BestEffort
  startTime: "2021-05-29T09:15:40Z"
